version: '2'

services:
  db:
    image: postgres:10.3-alpine
  
  redis:
    image: redis:5.0.9-alpine
      
  ci:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - CI
      - COVERAGE
      - RAILS_ENV
      - COVERALLS_REPO_TOKEN
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - REDIS_URL=redis://redis
    command: sh -c "bundle exec rails webpacker:install && bundle exec rails db:create db:migrate && bundle exec rake test"